# https://taplo.tamasfe.dev/configuration/formatter-options.html
include = ["Cargo.toml", "crates/**/*.toml", "tasks/**/*.toml"]

[formatting]
align_entries = true
column_width  = 120
reorder_keys  = true
