name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '!.github/workflows/ci.yml'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '!.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          bins: just, cargo-nextest
          cache-base: '^(main|develop-)'
          components: clippy

      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run linter
        run: just lint

      - name: Run Test
        run: just test

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-codspeed
          cache-base: '^(main|develop-)'
          components: clippy
      - name: Build Benchmark
        run: cargo codspeed build -p j2rs_find_up_simple
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: 'cargo codspeed run'
